spring:
  datasource:
    url: jdbc:mysql://192.168.1.98:3306/wmt?autoReconnect=true&amp&autoReconnectForPools=true&amp&useUnicode=true&amp&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver